// Package source decides which files hbb reads: files with a language the model knows,
// minus the folders it never enters, what .gitignore excludes (in a repository), the
// user's exclude globs, generated code and oversized files.
package source

import (
	"bytes"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"regexp"
	"slices"
	"strings"

	"github.com/bmatcuk/doublestar/v4"
)

// Filter is the rules a file must pass.
type Filter struct {
	Extensions    map[string]string // extension -> language (the bundle's)
	SkipDirs      []string          // folder names never entered (the bundle's)
	Exclude       []string          // globs (see Match)
	Include       []string          // when set, a file must match one of these
	SkipGenerated bool
	MaxBytes      int64 // 0: no limit
}

// Lang is the language of a path, "" when it is skipped by name: no known extension, a
// skipped folder, an exclude glob, or not included.
func (f *Filter) Lang(rel string) string {
	ext := path.Ext(rel)
	if ext == "" {
		return ""
	}
	lang := f.Extensions[strings.ToLower(ext[1:])]
	if lang == "" {
		return ""
	}
	dirs := strings.Split(rel, "/")
	for _, d := range dirs[:len(dirs)-1] {
		if slices.Contains(f.SkipDirs, d) {
			return ""
		}
	}
	if Match(f.Exclude, rel) {
		return ""
	}
	if len(f.Include) > 0 && !Match(f.Include, rel) {
		return ""
	}
	return lang
}

// Skip reports why a file's contents rule it out ("" to read it).
func (f *Filter) Skip(data []byte) string {
	if f.MaxBytes > 0 && int64(len(data)) > f.MaxBytes {
		return "too large"
	}
	if f.SkipGenerated && Generated(data) {
		return "generated"
	}
	return ""
}

var generatedRE = regexp.MustCompile(`(?m)^.{0,8}(Code generated .* DO NOT EDIT|@generated\b|<auto-generated)`)

// Generated reports whether a file declares itself generated in its first 2 KB: Go's
// "Code generated ... DO NOT EDIT.", "@generated", or .NET's "<auto-generated>".
func Generated(data []byte) bool {
	return generatedRE.Match(data[:min(len(data), 2048)])
}

// Match reports whether rel (slash-separated, relative to the root) matches any glob.
// Globs follow .gitignore conventions: "*" stays within a folder, "**" crosses them, a
// glob with no "/" matches a name at any depth ("*.min.js", "testdata"), a trailing "/"
// matches a folder and everything in it ("vendor/"), and a glob matching a folder
// matches everything in it.
func Match(globs []string, rel string) bool {
	for _, g := range globs {
		g = strings.TrimSpace(g)
		if g == "" {
			continue
		}
		g = strings.TrimSuffix(g, "/")
		if !strings.Contains(g, "/") {
			g = "**/" + g
		} else {
			g = strings.TrimPrefix(g, "/")
		}
		if ok, _ := doublestar.Match(g, rel); ok {
			return true
		}
		if ok, _ := doublestar.Match(g+"/**", rel); ok {
			return true
		}
	}
	return false
}

// File is a file to read.
type File struct {
	Rel  string // slash-separated, relative to the root: what window headers show
	Full string
	Lang string
}

// Walk lists the files under dir (inside root) that pass f by name, sorted, for a tree
// that is not a git repository (or when .gitignore should not count).
func Walk(root, dir string, f *Filter) ([]File, error) {
	var out []File
	err := filepath.WalkDir(dir, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			if p == dir {
				return err
			}
			return nil // unreadable folders are skipped
		}
		rel, rerr := filepath.Rel(root, p)
		if rerr != nil {
			return nil
		}
		rel = filepath.ToSlash(rel)
		if d.IsDir() {
			if p != dir && (slices.Contains(f.SkipDirs, d.Name()) || Match(f.Exclude, rel)) {
				return filepath.SkipDir
			}
			return nil
		}
		if !d.Type().IsRegular() {
			return nil // symbolic links and devices are not followed
		}
		if lang := f.Lang(rel); lang != "" {
			out = append(out, File{Rel: rel, Full: p, Lang: lang})
		}
		return nil
	})
	slices.SortFunc(out, func(a, b File) int { return strings.Compare(a.Rel, b.Rel) })
	return out, err
}

// FromList keeps the files of a list (from git) that pass f by name.
func FromList(root string, rels []string, f *Filter) []File {
	var out []File
	for _, rel := range rels {
		if lang := f.Lang(rel); lang != "" {
			full := filepath.Join(root, filepath.FromSlash(rel))
			if st, err := os.Lstat(full); err == nil && st.Mode().IsRegular() {
				out = append(out, File{Rel: rel, Full: full, Lang: lang})
			}
		}
	}
	slices.SortFunc(out, func(a, b File) int { return strings.Compare(a.Rel, b.Rel) })
	return out
}

// Text reports whether data looks like text (no NUL in the first 8 KB).
func Text(data []byte) bool { return bytes.IndexByte(data[:min(len(data), 8192)], 0) < 0 }
