package source

import "testing"

func TestMatch(t *testing.T) {
	for _, tc := range []struct {
		glob, path string
		want       bool
	}{
		{"vendor/", "vendor/x/y.go", true},
		{"vendor/", "src/vendor/y.go", true},
		{"vendor/", "vendors/y.go", false},
		{"*.min.js", "web/a/app.min.js", true},
		{"*.min.js", "app.js", false},
		{"test/*", "test/a.go", true},
		{"test/*", "test/a/b.go", true}, // a folder match covers its contents
		{"src/**/gen_*.go", "src/a/b/gen_x.go", true},
		{"/build", "build/x.c", true},
		{"/build", "src/build/x.c", false},
		{"testdata", "pkg/testdata/f.py", true},
	} {
		if got := Match([]string{tc.glob}, tc.path); got != tc.want {
			t.Errorf("Match(%q, %q) = %v, want %v", tc.glob, tc.path, got, tc.want)
		}
	}
}

func TestFilter(t *testing.T) {
	f := &Filter{Extensions: map[string]string{"py": "python", "go": "go"}, SkipDirs: []string{"node_modules"},
		Exclude: []string{"*_test.go"}, SkipGenerated: true, MaxBytes: 10}
	for path, want := range map[string]string{
		"a.py": "python", "A.PY": "python", "x/node_modules/a.py": "", "a_test.go": "", "a.txt": "", "Makefile": "",
	} {
		if got := f.Lang(path); got != want {
			t.Errorf("Lang(%q) = %q, want %q", path, got, want)
		}
	}
	if f.Skip([]byte("01234567890")) != "too large" {
		t.Error("size limit")
	}
	if !Generated([]byte("// Code generated by protoc-gen-go. DO NOT EDIT.\npackage x")) || Generated([]byte("package x")) {
		t.Error("generated detection")
	}
}
